### ISSUE TITLE
Choose Dataset for testing purposes

### ISSUE THREAD

**Issue by nd265** [UBC-MDS-2021-22/simplefit#12]

**Comment by nd265** [comment]
Hi @zzhzoe @rezam747 @Sanchit120496 , I think we can use the [Spotify dataset](https://www.kaggle.com/zaheenhamidani/ultimate-spotify-tracks-db) for regression task and [Spotify attributes dataset](https://www.kaggle.com/geomack/spotifyclassification) for classification task. Let me know if you guys feel you are okay with it. Else, feel free to suggest other datasets for testing purposes later in our project

**Comment by zzhzoe** [comment]
I am good with this datasets, thank your for finding.

**Comment by rezam747** [comment]
Just to make sure. The target column in Spotify dataset for the regression task is popularity. right?

**Comment by nd265** [comment]
> Just to make sure. The target column in Spotify dataset for the regression task is popularity. right?

Yes @rezam747 , the target column is popularity for regression
