### ISSUE TITLE
License Discussion 

### ISSUE THREAD

**Issue by zzhzoe** [UBC-MDS-2021-22/simplefit#66]
Hey guys,
     I am opening an issue to select a license for our project. I suggest visiting [choosealicense.com.](https://choosealicense.com./) From there you can browse and present your personal preferences. From there we will discuss the pros and cons of each license preference. 
My preference:  MIT License

I chose this license because it is simple and covers the basic usage of our project. We are already using it. I believe the MIT License is a good idea and everyone is familiar with it. It helps our package viewers to understand the copyright rules of our project. In addition, I think the conditions listed in the MIT License serve the purposes of our project well. That is, it allows others to do what they want with our project while retaining the copyright.

we want to make sure the package is available for use, distribution and release. In short, we promote this package as open source. The purpose of this package is not to generate profits, but simply to help users use their time efficiently when performing exploratory data analysis. The [MIT License](https://choosealicense.com./licenses/mit/) is short and to the point. It lets people do almost anything they want with your project, like making and distributing closed source versions. I think our licenses should be short and to the point. I am not picky if people distribute closed source versions of our package code or want to modify it to suit their needs. Based on this criteria, I believe the MIT license is perfect for our needs

**Comment by nd265** [comment]
I agree with you @zzhzoe , I think MIT license would be the best suited license for our project. It is short and easy to use and also helps our package viewers to understand the copyright rules of our project. We can go ahead with the MIT license

**Comment by Sanchit120496** [comment]
Agreed, The MIT license is one of the most permissive software licenses out there. The MIT license is a great choice because it allows one to share ones code under a copyleft license without forcing others to expose their proprietary code. And as Zoe mentioned, the license is very short relative to other open source licenses.

**Comment by rezam747** [comment]
I also agree that the MIT license is the best fit for our project. First, this license makes life easier for contributors and users as they are more likely to already be familiar with the condition and limitations of this license. Second, as our project is a package and we would like to let people do almost anything they want with our project, like making and distributing closed source versions, it aligns with our goals.

**Comment by zzhzoe** [comment]
Final decision: MIT license
